### ISSUE TITLE
希望能够支持任意前缀的命令

### ISSUE THREAD

**Issue by he0119** [monsterxcn/nonebot-plugin-gscode#4]
https://github.com/monsterxcn/nonebot-plugin-gscode/blob/74c968b30da0bc6c97e357dc0818e87938e8c4ab/nonebot_plugin_gscode/__init__.py#L13-L14

请问限制命令前缀为无是有什么考量吗？如果用 `/兑换码` 会直接退出执行。

**Comment by monsterxcn** [comment]
写错了应该，下次改一下… 本意是想不响应命令后附带任何内容的消息，避免误触发。

大概应该用 `if not str(state["_prefix"]["command_arg"])` 什么的

**Comment by he0119** [comment]
原来如此，那你其实可以判断一下 CommandArg 是不是为空。
