### ISSUE TITLE
活动已结束 (-500012)

### ISSUE THREAD

**Issue by Tosd0** [monsterxcn/nonebot-plugin-gscode#6]
昨天发现获取到的验证码是3.6的 我顺着测试了一下，mys的act_id 从 20230331ys6933改成了ea202305082049522228
然后代入`https://api-takumi.mihoyo.com/event/bbslive/index?act_id=ea202305082049522228`
就会报活动已结束
![7C0A78CC-5601-4485-97FE-4048C7A21A1B](https://github.com/monsterxcn/nonebot-plugin-gscode/assets/65720409/df12076d-b3e6-4b76-8801-f8e45593a8ef)
我不太会 不知道能不能通过直接获取直播间的html内容，然后匹配验证码正则解决（）他直播间里有兑换码

**Comment by monsterxcn** [comment]
谁直播间？

**Comment by Tosd0** [comment]
> 谁直播间？

https://webstatic.mihoyo.com/bbs/event/live/index.html?act_id=ea202305082049522228&mhy_presentation_style=fullscreen&game_biz=hk4e&utm_source=bbs&utm_medium=mys&utm_campaign=arti
![image](https://github.com/monsterxcn/nonebot-plugin-gscode/assets/65720409/35009de3-b5d7-4252-97b2-224816964232)
这里会有三个兑换码

**Comment by monsterxcn** [comment]
好的有空来看下，昨天简单看了下没找到这个网址
