### ISSUE TITLE
KeyError: 'post id'

### ISSUE THREAD

**Issue by xi-yue-233** [monsterxcn/nonebot-plugin-gscode#9]
![L$ )T}@51NH5YPSV QWWGTG](https://github.com/monsterxcn/nonebot-plugin-gscode/assets/58218656/eb14a3b8-55f6-43e2-966b-a17f63210d4f)

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/nonebot-plugin-gscode/blob/83c6cb69426444073e64947508e372c0c24f8db7/nonebot_plugin_gscode/data_source.py#L90-L91

```diff
    if live_data_raw["is_end"]:
-       live_data["review"] = live_template["reviewUrl"]["args"]["post_id"]
+       live_data["review"] = live_template["reviewUrl"]["args"].get("post_id")
```

**Comment by monsterxcn** [comment]
不太懂啊，就是回放的那个帖子 ID 为啥又不在这里了，上次抓的时候这里时能拿到那个帖子 ID 的
